### PR TITLE
Added autoHighlight option

### PR DESCRIPTION
**Pull request by cbess**
The user/dev now has the ability to disable auto-highlighting of the first result. Allowing the users to press [enter] to submit the field's value, rather than it selecting the first result, and submitting that instead. A better reflection of Google auto-complete, etc.

### CODE REVIEW

**Comment by cbess** [comment]
A good real-world example can be found at:
http://116music.com

In the search box at the top, type **before**, wait for auto complete results.

The site uses the autoHighlight:false option.

**Comment by betamos** [comment]
Sorry for very late answer. I like this feature!
What I do not like is the this.form.submit() part since that is not necessarily the desirable action.
Currently BAC depends on the select callback, but since a selection isn't made, there is no natural action to do.

What do you think about this? If autoselect is off and a select key (enter) is pressed while nothing is selected, a callback is fired. Probably we would need another callback than select, to avoid confusion. That callback could take the desired search string as an argument. In that callback, the form submission (or any other action) could be made by the integrating developer.

**Comment by cbess** [comment]
Great, I hope the feature helps others as well.

Yes, I agree. You could call the [enter] key callback `selectKeyPressed` or something, then pass in the number of results suggested and the search string.

**Comment by balintbrews** [comment]
I would like to fully mimic the bevahior of google.com's autocomplete, which essentially automatically selects items when you use the arrow keys. I used this pull request as a start, and implemented the feature as a new option. [I requested from cbess to pull my code](https://github.com/cbess/Better-Autocomplete/pull/1) in his repository, so we don't work on different forks, and eventually if he's convinced, my work will be part of this pull request, so we are all on the same track. In the meantime, I would love to hear your opinion betamos. Thank you for this great plugin btw. :)

**Comment by betamos** [comment]
Hello again. I am terribly sorry that I am making so slow progress on this. I have now implemented the `autoHighlight` option (defualt true). See develop branch. I used some of the code from you cbess, thanks. Instead of building on your commits, I made my own and mentioned you there instead, hope that's okay with you.

I will now continue with the "google replication" stuff. I have some different ideas about this than balintk, but in general the purpose would be the same. I believe that instead of an `autoSelect` option, there should be a `highlight` callback. The function `reprocess` is difficult to understand (I barely understand it myself :) and I do not want to expose that word to the user. If information about the event (mouseover, keydown etc) is passed to the highlight callback, it would be fairly easy to replicate the Google-like autocompletion.

Thanks all for contributing and using BAC! Thoughts are welcome.

**Comment by cbess** [comment]
As long as others have access to the functionality I'm happy. Thanks for the attribution and the clean codebase!

**Pull request closed without merging**
